import { useEffect, useMemo, useState } from "react";
import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "@/hooks/use-toast";
import { CalendarDays, ChevronLeft, ChevronRight, Filter, History, RefreshCw } from "lucide-react";

type Funnel={id:string;name:string};
type Task={id:string;funnel_id:string;title:string;status:string;priority:string;owner:string|null;due_date:string|null};
type Snapshot={id:string;funnel_id:string;progress:number;total_tasks:number;completed_tasks:number;overdue_tasks:number;blocked_tasks:number;recorded_at:string};
const db=supabase as any;
const statusLabel:Record<string,string>={todo:"A fazer",doing:"Em andamento",review:"Revisão",blocked:"Bloqueada",done:"Concluída"};
const priorityLabel:Record<string,string>={low:"Baixa",medium:"Média",high:"Alta",urgent:"Urgente"};
const iso=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;

export default function StrategyCalendar(){
 const [funnels,setFunnels]=useState<Funnel[]>([]),[tasks,setTasks]=useState<Task[]>([]),[history,setHistory]=useState<Snapshot[]>([]),[loading,setLoading]=useState(true);
 const [month,setMonth]=useState(()=>new Date()),[owner,setOwner]=useState("all"),[status,setStatus]=useState("all"),[priority,setPriority]=useState("all"),[funnel,setFunnel]=useState("all");
 const load=async()=>{setLoading(true);const [f,t,h]=await Promise.all([db.from("strategy_funnels").select("id,name").order("updated_at",{ascending:false}),db.from("strategy_tasks").select("id,funnel_id,title,status,priority,owner,due_date").order("due_date",{ascending:true}),db.from("strategy_progress_history").select("*").order("recorded_at",{ascending:false}).limit(300)]);if(f.error||t.error){toast({title:"Falha ao carregar calendário",description:f.error?.message||t.error?.message,variant:"destructive"});}else{setFunnels(f.data||[]);setTasks(t.data||[]);setHistory(h.data||[]);}setLoading(false)};
 useEffect(()=>{load()},[]);
 const owners=useMemo(()=>Array.from(new Set(tasks.map(t=>t.owner).filter(Boolean) as string[])).sort(),[tasks]);
 const filtered=useMemo(()=>tasks.filter(t=>(owner==="all"||t.owner===owner)&&(status==="all"||t.status===status)&&(priority==="all"||t.priority===priority)&&(funnel==="all"||t.funnel_id===funnel)),[tasks,owner,status,priority,funnel]);
 const first=new Date(month.getFullYear(),month.getMonth(),1),last=new Date(month.getFullYear(),month.getMonth()+1,0),start=new Date(first);start.setDate(first.getDate()-first.getDay());const days=Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d});
 const name=(id:string)=>funnels.find(f=>f.id===id)?.name||"Estratégia";
 const capture=async()=>{const ids=funnel==="all"?funnels.map(f=>f.id):[funnel];for(const id of ids){const {error}=await db.rpc("capture_strategy_progress_snapshot",{p_funnel_id:id});if(error){toast({title:"Histórico ainda não disponível",description:error.message,variant:"destructive"});return}}toast({title:"Progresso registrado",description:"Snapshot salvo no histórico das estratégias."});load()};
 const historyRows=useMemo(()=>{const ids=funnel==="all"?funnels.map(f=>f.id):[funnel];return ids.map(id=>{const rows=history.filter(h=>h.funnel_id===id);return {id,name:name(id),current:rows[0],previous:rows[1]}}).filter(x=>x.current)},[history,funnel,funnels]);
 return <DashboardLayout><div className="space-y-6">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-extralight">Calendário & Evolução</h1><p className="text-muted-foreground mt-1">Prazos mensais, filtros operacionais e histórico de progresso das estratégias.</p></div><div className="flex gap-2"><Button variant="outline" onClick={capture}><History className="h-4 w-4 mr-2"/>Registrar progresso</Button><Button variant="outline" onClick={load}><RefreshCw className="h-4 w-4 mr-2"/>Atualizar</Button></div></div>
  <div className="grid gap-3 md:grid-cols-4 rounded-2xl border bg-card/40 p-4"><label className="text-xs text-muted-foreground"><Filter className="inline h-3 w-3 mr-1"/>Estratégia<select className="mt-1 w-full rounded-lg border bg-background p-2" value={funnel} onChange={e=>setFunnel(e.target.value)}><option value="all">Todas</option>{funnels.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label className="text-xs text-muted-foreground">Responsável<select className="mt-1 w-full rounded-lg border bg-background p-2" value={owner} onChange={e=>setOwner(e.target.value)}><option value="all">Todos</option>{owners.map(o=><option key={o}>{o}</option>)}</select></label><label className="text-xs text-muted-foreground">Status<select className="mt-1 w-full rounded-lg border bg-background p-2" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Todos</option>{Object.entries(statusLabel).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="text-xs text-muted-foreground">Prioridade<select className="mt-1 w-full rounded-lg border bg-background p-2" value={priority} onChange={e=>setPriority(e.target.value)}><option value="all">Todas</option>{Object.entries(priorityLabel).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div>
  <section className="rounded-2xl border bg-card/30 overflow-hidden"><div className="flex items-center justify-between p-4 border-b"><Button variant="ghost" size="icon" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}><ChevronLeft/></Button><div className="flex items-center gap-2 font-medium"><CalendarDays className="h-4 w-4"/>{month.toLocaleDateString("pt-BR",{month:"long",year:"numeric"})}</div><Button variant="ghost" size="icon" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}><ChevronRight/></Button></div><div className="grid grid-cols-7 text-center text-xs text-muted-foreground border-b">{["Dom","Seg","Ter","Qua","Qui","Sex","Sáb"].map(x=><div className="p-2" key={x}>{x}</div>)}</div><div className="grid grid-cols-7">{days.map(d=>{const key=iso(d),items=filtered.filter(t=>t.due_date===key);return <div key={key} className={`min-h-28 border-b border-r p-2 ${d.getMonth()!==month.getMonth()?"opacity-40":""}`}><div className="text-xs mb-2">{d.getDate()}</div><div className="space-y-1">{items.slice(0,4).map(t=><div key={t.id} className="rounded-md border bg-background/70 p-1.5 text-[10px]"><div className="font-medium truncate">{t.title}</div><div className="text-muted-foreground truncate">{name(t.funnel_id)} · {priorityLabel[t.priority]||t.priority}</div></div>)}{items.length>4&&<div className="text-[10px] text-muted-foreground">+{items.length-4} tarefas</div>}</div></div>})}</div></section>
  <section className="rounded-2xl border bg-card/30 p-4"><h2 className="font-medium mb-4">Histórico de progresso</h2>{loading?<p className="text-sm text-muted-foreground">Carregando...</p>:historyRows.length===0?<p className="text-sm text-muted-foreground">Clique em “Registrar progresso” para criar o primeiro snapshot.</p>:<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{historyRows.map(r=>{const delta=r.previous?r.current.progress-r.previous.progress:0;return <div key={r.id} className="rounded-xl border bg-background/50 p-4"><div className="font-medium truncate">{r.name}</div><div className="flex items-end gap-2 mt-3"><span className="text-3xl font-light">{r.current.progress}%</span><span className={`text-xs mb-1 ${delta<0?"text-red-400":"text-muted-foreground"}`}>{delta>0?"+":""}{delta} pts</span></div><div className="mt-3 h-2 rounded-full bg-muted overflow-hidden"><div className="h-full bg-primary" style={{width:`${r.current.progress}%`}}/></div><div className="grid grid-cols-3 gap-2 mt-3 text-[10px] text-muted-foreground"><span>{r.current.completed_tasks}/{r.current.total_tasks} concluídas</span><span>{r.current.overdue_tasks} vencidas</span><span>{r.current.blocked_tasks} bloqueadas</span></div></div>})}</div>}</section>
 </div></DashboardLayout>
}
